AWSTemplateFormatVersion: "2010-09-09"
Description: Template to create a VPC with public and private subnets.

Parameters:
  VpcCidr:
    Description: The CIDR block for the VPC
    Type: String
    Default: 172.16.0.0/16
  PublicSubnetCidr:
    Description: CIDR block for the public subnet
    Type: String
    Default: 172.16.1.0/24
  PrivateSubnetCidr:
    Description: CIDR block for the private subnet
    Type: String
    Default: 172.16.2.0/24

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock:
        Ref: VpcCidr
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: VPC

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PublicSubnetCidr
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: PublicSubnet

  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PrivateSubnetCidr
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: PrivateSubnet

Outputs:
  VpcId:
    Description: The ID of the created VPC
    Value: !Ref VPC
  PublicSubnetId:
    Description: The ID of the public subnet
    Value: !Ref PublicSubnet
  PrivateSubnetId:
    Description: The ID of the private subnet
    Value: !Ref PrivateSubnet
